from __future__ import annotations

import uuid

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.golf_course import GolfCourse

# Fields that constitute the GPS calibration block.
# Used to detect "row exists but has no GPS data" and to drive targeted updates.
_GPS_FIELDS: tuple[str, ...] = (
    "center_lat",
    "center_lng",
    "bound_north",
    "bound_south",
    "bound_east",
    "bound_west",
    "default_zoom",
)

_COURSES: list[dict] = [
    {
        "name_ko": "베어즈베스트청라",
        "name": "Bears Best Cheongna",
        "address_ko": "인천광역시 서구 청라대로316번길 45",
        "address": "Cheongna-daero 316beon-gil 45 Incheon",
        "center_lat": 37.5383,
        "center_lng": 126.6441,
        "bound_north": 37.5430,
        "bound_south": 37.5336,
        "bound_east": 126.6510,
        "bound_west": 126.6372,
        "default_zoom": 16,
    },
    {
        "name_ko": "정남진골프클럽",
        "name": "Jeongnamjin Golf Club",
        "address_ko": "전라남도 장흥군",
        "address": "Jangheung-gun Jeollanam-do",
        "center_lat": 34.6833,
        "center_lng": 126.9167,
        "bound_north": 34.6890,
        "bound_south": 34.6776,
        "bound_east": 126.9240,
        "bound_west": 126.9094,
        "default_zoom": 16,
    },
    {
        "name_ko": "파인리즈CC",
        "name": "Pine Liz CC",
        "address_ko": "강원도 고성군 토성면 잼버리동로 267",
        "address": "Jambeori-dongro 267 Goseong Gangwon",
        "center_lat": 38.2833,
        "center_lng": 128.5667,
        "bound_north": 38.2900,
        "bound_south": 38.2766,
        "bound_east": 128.5750,
        "bound_west": 128.5584,
        "default_zoom": 16,
    },
    {
        "name_ko": "디오션골프클럽",
        "name": "The Ocean Golf Club",
        "address_ko": "전라남도 해남군",
        "address": "Haenam-gun Jeollanam-do",
        "center_lat": 34.5500,
        "center_lng": 126.5833,
        "bound_north": 34.5567,
        "bound_south": 34.5433,
        "bound_east": 126.5910,
        "bound_west": 126.5756,
        "default_zoom": 16,
    },
    {
        "name_ko": "용평CC",
        "name": "Yongpyong CC",
        "address_ko": "강원특별자치도 평창군 대관령면 올림픽로 715",
        "address": "Olympic-ro 715 Pyeongchang Gangwon",
        "center_lat": 37.6583,
        "center_lng": 128.6722,
        "bound_north": 37.6650,
        "bound_south": 37.6516,
        "bound_east": 128.6800,
        "bound_west": 128.6644,
        "default_zoom": 16,
    },
    {
        "name_ko": "핀크스골프클럽",
        "name": "Pinx Golf Club",
        "address_ko": "제주특별자치도 서귀포시 안덕면 산록남로 863",
        "address": "Sangnok-namro 863 Seogwipo Jeju",
        "center_lat": 33.3167,
        "center_lng": 126.3667,
        "bound_north": 33.3234,
        "bound_south": 33.3100,
        "bound_east": 126.3750,
        "bound_west": 126.3584,
        "default_zoom": 16,
    },
    {
        "name_ko": "구미마이다스CC",
        "name": "Midas Golf Gumi",
        "address_ko": "경상북도 칠곡군 가산면 학하리",
        "address": "Hakha-ri Gasan-myeon Chilgok Gyeongbuk",
        "center_lat": 36.0833,
        "center_lng": 128.5000,
        "bound_north": 36.0900,
        "bound_south": 36.0766,
        "bound_east": 128.5080,
        "bound_west": 128.4920,
        "default_zoom": 16,
    },
    {
        "name_ko": "이천마이다스CC",
        "name": "Midas Lake Icheon",
        "address_ko": "경기도 이천시",
        "address": "Icheon-si Gyeonggi-do",
        "center_lat": 37.2722,
        "center_lng": 127.4417,
        "bound_north": 37.2789,
        "bound_south": 37.2655,
        "bound_east": 127.4500,
        "bound_west": 127.4334,
        "default_zoom": 16,
    },
    {
        "name_ko": "360도골프클럽",
        "name": "360 Golf Club",
        "address_ko": "경기도 양평군",
        "address": "Yangpyeong-gun Gyeonggi-do",
        "center_lat": 37.5000,
        "center_lng": 127.5833,
        "bound_north": 37.5067,
        "bound_south": 37.4933,
        "bound_east": 127.5910,
        "bound_west": 127.5756,
        "default_zoom": 16,
    },
    {
        "name_ko": "제이퍼블릭골프클럽",
        "name": "J Public Golf Club",
        "address_ko": "경기도 파주시",
        "address": "Paju-si Gyeonggi-do",
        "center_lat": 37.7833,
        "center_lng": 126.7500,
        "bound_north": 37.7900,
        "bound_south": 37.7766,
        "bound_east": 126.7580,
        "bound_west": 126.7420,
        "default_zoom": 16,
    },
    {
        "name_ko": "메이플비치골프클럽",
        "name": "Maple Beach Golf Club",
        "address_ko": "강원도 동해시",
        "address": "Donghae-si Gangwon-do",
        "center_lat": 37.5167,
        "center_lng": 129.1167,
        "bound_north": 37.5234,
        "bound_south": 37.5100,
        "bound_east": 129.1250,
        "bound_west": 129.1084,
        "default_zoom": 16,
    },
    {
        "name_ko": "버치힐골프클럽",
        "name": "Birch Hill Golf Club",
        "address_ko": "경기도 가평군",
        "address": "Gapyeong-gun Gyeonggi-do",
        "center_lat": 37.7500,
        "center_lng": 127.4833,
        "bound_north": 37.7567,
        "bound_south": 37.7433,
        "bound_east": 127.4910,
        "bound_west": 127.4756,
        "default_zoom": 16,
    },
    {
        "name_ko": "사이프러스골프앤리조트",
        "name": "Cypress Golf and Resort",
        "address_ko": "제주특별자치도 제주시",
        "address": "Jeju-si Jeju-do",
        "center_lat": 33.4500,
        "center_lng": 126.5667,
        "bound_north": 33.4567,
        "bound_south": 33.4433,
        "bound_east": 126.5750,
        "bound_west": 126.5584,
        "default_zoom": 15,
    },
    {
        "name_ko": "캐슬파인골프클럽",
        "name": "Castle Pines Golf Club",
        "address_ko": "충청남도",
        "address": "Chungcheongnam-do",
        "center_lat": 36.5000,
        "center_lng": 127.0000,
        "bound_north": 36.5067,
        "bound_south": 36.4933,
        "bound_east": 127.0080,
        "bound_west": 126.9920,
        "default_zoom": 16,
    },
    {
        "name_ko": "롯데스카이힐제주CC",
        "name": "Lotte Skyhill Jeju CC",
        "address_ko": "제주특별자치도 서귀포시",
        "address": "Seogwipo-si Jeju-do",
        "center_lat": 33.2833,
        "center_lng": 126.5000,
        "bound_north": 33.2900,
        "bound_south": 33.2766,
        "bound_east": 126.5080,
        "bound_west": 126.4920,
        "default_zoom": 15,
    },
    {
        "name_ko": "성문안골프클럽",
        "name": "Seongmunan Golf Club",
        "address_ko": "경기도",
        "address": "Gyeonggi-do",
        "center_lat": 37.3500,
        "center_lng": 127.1667,
        "bound_north": 37.3567,
        "bound_south": 37.3433,
        "bound_east": 127.1750,
        "bound_west": 127.1584,
        "default_zoom": 16,
    },
    {
        "name_ko": "오크밸리CC",
        "name": "Oak Valley CC",
        "address_ko": "강원도 횡성군",
        "address": "Hoengseong-gun Gangwon-do",
        "center_lat": 37.4833,
        "center_lng": 127.9667,
        "bound_north": 37.4900,
        "bound_south": 37.4766,
        "bound_east": 127.9750,
        "bound_west": 127.9584,
        "default_zoom": 16,
    },
    {
        "name_ko": "김제스파힐스CC",
        "name": "Gimje Spa Hills CC",
        "address_ko": "전라북도 김제시 온천길 37",
        "address": "Oncheon-gil 37 Gimje Jeollabuk-do",
        "center_lat": 35.8000,
        "center_lng": 126.8833,
        "bound_north": 35.8067,
        "bound_south": 35.7933,
        "bound_east": 126.8910,
        "bound_west": 126.8756,
        "default_zoom": 16,
    },
    {
        "name_ko": "소피아그린골프클럽",
        "name": "Sofia Green Golf Club",
        "address_ko": "경기도",
        "address": "Gyeonggi-do",
        "center_lat": 37.4167,
        "center_lng": 127.2500,
        "bound_north": 37.4234,
        "bound_south": 37.4100,
        "bound_east": 127.2580,
        "bound_west": 127.2420,
        "default_zoom": 16,
    },
    {
        "name_ko": "카스카디아골프클럽",
        "name": "Cascadia Golf Club",
        "address_ko": "경기도",
        "address": "Gyeonggi-do",
        "center_lat": 37.5500,
        "center_lng": 127.3333,
        "bound_north": 37.5567,
        "bound_south": 37.5433,
        "bound_east": 127.3410,
        "bound_west": 127.3256,
        "default_zoom": 16,
    },
    {
        "name_ko": "청평마이다스CC",
        "name": "Midas Valley Cheongpyeong",
        "address_ko": "경기도 가평군",
        "address": "Gapyeong-gun Gyeonggi-do",
        "center_lat": 37.7167,
        "center_lng": 127.4167,
        "bound_north": 37.7234,
        "bound_south": 37.7100,
        "bound_east": 127.4250,
        "bound_west": 127.4084,
        "default_zoom": 16,
    },
    {
        "name_ko": "드비치골프클럽",
        "name": "The Beach Golf Club",
        "address_ko": "제주특별자치도",
        "address": "Jeju-do",
        "center_lat": 33.5000,
        "center_lng": 126.8333,
        "bound_north": 33.5067,
        "bound_south": 33.4933,
        "bound_east": 126.8410,
        "bound_west": 126.8256,
        "default_zoom": 16,
    },
    {
        "name_ko": "솔트베이골프클럽",
        "name": "Salt Bay Golf Club",
        "address_ko": "경기도 시흥시",
        "address": "Siheung-si Gyeonggi-do",
        "center_lat": 37.3667,
        "center_lng": 126.7333,
        "bound_north": 37.3734,
        "bound_south": 37.3600,
        "bound_east": 126.7410,
        "bound_west": 126.7256,
        "default_zoom": 16,
    },
    {
        "name_ko": "중부골프클럽",
        "name": "Jungbu Golf Club",
        "address_ko": "경기도",
        "address": "Gyeonggi-do",
        "center_lat": 37.2000,
        "center_lng": 127.5000,
        "bound_north": 37.2067,
        "bound_south": 37.1933,
        "bound_east": 127.5080,
        "bound_west": 127.4920,
        "default_zoom": 16,
    },
    {
        "name_ko": "오로라골프클럽",
        "name": "Aurora Golf Club",
        "address_ko": "경기도",
        "address": "Gyeonggi-do",
        "center_lat": 37.6500,
        "center_lng": 127.1667,
        "bound_north": 37.6567,
        "bound_south": 37.6433,
        "bound_east": 127.1750,
        "bound_west": 127.1584,
        "default_zoom": 16,
    },
]


async def seed_daejung_courses(db: AsyncSession) -> None:
    """Upsert the 25 Daejung Golf course records.

    - Insert if name_ko is not found.
    - Update GPS fields if the row exists but center_lat is NULL.
    - Skip if the row exists and center_lat is already set.
    """
    inserted = updated = skipped = 0

    for data in _COURSES:
        result = await db.execute(
            select(GolfCourse).where(GolfCourse.name_ko == data["name_ko"])
        )
        existing = result.scalar_one_or_none()

        if existing is None:
            db.add(GolfCourse(id=uuid.uuid4(), is_active=True, **data))
            inserted += 1
        elif existing.center_lat is None:
            for field in _GPS_FIELDS:
                setattr(existing, field, data[field])
            updated += 1
        else:
            skipped += 1

    await db.commit()
    print(
        f"[seed_daejung_courses] done: "
        f"inserted={inserted} updated={updated} skipped={skipped}"
    )
