"""add_gps_bounds_to_golf_courses

Revision ID: ea4fce96ce0c
Revises: e6f7a8b9c0d1
Create Date: 2026-05-29 12:23:02.057887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea4fce96ce0c'
down_revision: Union[str, Sequence[str], None] = 'e6f7a8b9c0d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_drone_scans_created_at'), table_name='drone_scans')
    op.drop_index(op.f('ix_drone_scans_status'), table_name='drone_scans')
    op.add_column('golf_courses', sa.Column('center_lat', sa.Float(), nullable=True))
    op.add_column('golf_courses', sa.Column('center_lng', sa.Float(), nullable=True))
    op.add_column('golf_courses', sa.Column('bound_north', sa.Float(), nullable=True))
    op.add_column('golf_courses', sa.Column('bound_south', sa.Float(), nullable=True))
    op.add_column('golf_courses', sa.Column('bound_east', sa.Float(), nullable=True))
    op.add_column('golf_courses', sa.Column('bound_west', sa.Float(), nullable=True))
    op.add_column('golf_courses', sa.Column('default_zoom', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_issues_course_status_priority'), table_name='issues')
    op.create_index(op.f('ix_issues_course_id'), 'issues', ['course_id'], unique=False)
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_created'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_read_created'), table_name='notifications')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_notifications_user_read_created'), 'notifications', ['user_id', 'is_read', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_notifications_user_created'), 'notifications', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.drop_index(op.f('ix_issues_course_id'), table_name='issues')
    op.create_index(op.f('ix_issues_course_status_priority'), 'issues', ['course_id', 'status', 'priority'], unique=False)
    op.drop_column('golf_courses', 'default_zoom')
    op.drop_column('golf_courses', 'bound_west')
    op.drop_column('golf_courses', 'bound_east')
    op.drop_column('golf_courses', 'bound_south')
    op.drop_column('golf_courses', 'bound_north')
    op.drop_column('golf_courses', 'center_lng')
    op.drop_column('golf_courses', 'center_lat')
    op.create_index(op.f('ix_drone_scans_status'), 'drone_scans', ['status'], unique=False)
    op.create_index(op.f('ix_drone_scans_created_at'), 'drone_scans', ['created_at'], unique=False)
    # ### end Alembic commands ###
